### ISSUE TITLE
Failed to start MainActivity

### ISSUE THREAD

**Issue by gaojingwen945** [uelordi01/Call_RenderScript_from_NDK#3]
Everytime the activity crashes immediately after start, throwing the following exception:
```
E/AndroidRuntime(25917): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/uelordi.android.hellocomputendk_rs-1/base.apk"],nativeLibraryDirectories=[/data/app/uelordi.android.hellocomputendk_rs-1/lib/arm, /data/app/uelordi.android.hellocomputendk_rs-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib]]] couldn't find "libnative-lib.so"
```
which is just the same as what I get in my own demo...
Do you have any ideas? My phone is Meizu Pro 7Plus, 7.0.0. Same with Smartisan 7.1.1. 
Update: Well, it is ok with Motorola Nexus 6, 7.1.1.

**Comment by uelordi01** [comment]
Hi gaojingwen945:
Sorry for my delay
it seems that the compiler does not find the main library of ndk (libnaitve-lib.so)
this is probably because when you are deploying the project to run (this native-lib) is not loaded 
check this function **System.loadLibrary("native-lib")** and try to put a general exception. 
try to deploy your apk and open with a zip archiver an see if this native-lib is placed inside.
